"""LLM-backed trip-shape generation for selected destinations.

This service is intentionally fail-closed: when the LLM is disabled, missing a key,
or returns invalid JSON, callers receive ``None`` and can use deterministic fallback
planning. It never claims live prices, inventory, flight numbers, room layouts, or
booking terms.
"""

from __future__ import annotations

import json
import re
from typing import Any

import anthropic

from trippy import config
from trippy.memory.store import MemoryStore
from trippy.models.preferences import FamilyTravelPreferences
from trippy.models.trip_planning import TripIntake, TripPlanDraft, TripPlanOption
from trippy.services.country_priors import CountryPriorService

_PROMPT_VERSION = "llm-trip-shapes-v1"
_MAX_TOKENS = 3200


class LLMTripShapeService:
    """Generate destination-specific trip-shape options from an actual intake."""

    def __init__(
        self,
        *,
        preferences: FamilyTravelPreferences | None = None,
        memory: MemoryStore | None = None,
        country_priors: CountryPriorService | None = None,
        anthropic_client: Any | None = None,
        enabled: bool | None = None,
        model: str | None = None,
    ) -> None:
        self._prefs = preferences or FamilyTravelPreferences()
        self._memory = memory or MemoryStore(config.MEMORY_PATH)
        self._country_priors = country_priors or CountryPriorService()
        self._client = anthropic_client
        self._enabled = config.TRIP_SHAPE_LLM_ENABLED if enabled is None else enabled
        self._model = model or config.TRIP_SHAPE_LLM_MODEL

    def build(self, intake: TripIntake) -> TripPlanDraft | None:
        """Return a tailored draft, or ``None`` when the deterministic fallback should run."""
        if not self._enabled:
            return None
        if not intake.destination_seeds:
            return None
        if not config.ANTHROPIC_API_KEY and self._client is None:
            return None
        try:
            prompt = self._prompt(intake)
            client = self._client or anthropic.Anthropic(api_key=config.ANTHROPIC_API_KEY)
            response = client.messages.create(
                model=self._model,
                max_tokens=_MAX_TOKENS,
                system=(
                    "You are Trippy's evidence-bound senior family travel planner. "
                    "Return valid JSON only. Never invent live inventory, prices, booking terms, or flight facts."
                ),
                messages=[{"role": "user", "content": prompt}],
            )
            parsed = _parse_json_response(_response_text(response))
            options = _options_from_payload(parsed, intake)
            if len(options) < 2:
                return None
            recommended = str(parsed.get("recommended_option_id") or "")
            if recommended not in {option.option_id for option in options}:
                recommended = max(options, key=lambda option: option.recommendation_strength).option_id
            assumptions = _string_list(parsed.get("assumptions"))
            if not assumptions:
                assumptions = [
                    "LLM generated destination-specific trip shapes from the current intake.",
                    "Scores are planning-shape confidence, not live price, inventory, or booking availability.",
                ]
            return TripPlanDraft(
                trip_id=intake.trip_id,
                intake_mode=intake.mode,
                options=options[:3],
                recommended_option_id=recommended,
                assumptions=assumptions,
                source_notes=[
                    f"Generated by {_PROMPT_VERSION} using {self._model}.",
                    "Uses intake, family preferences, memory context, and matched country priors; exact travel products still require live shortlists.",
                ],
            )
        except Exception:
            return None

    def _prompt(self, intake: TripIntake) -> str:
        destination_text = " ".join(
            [intake.trip_name, *intake.destination_seeds, intake.freeform_notes or ""]
        )
        country_signals = [
            signal.model_dump(mode="json")
            for signal in self._country_priors.fit_for_text(destination_text)
        ]
        memory_context = self._memory.to_context_string()
        payload = {
            "trip_id": intake.trip_id,
            "trip_name": intake.trip_name,
            "destination_seeds": intake.destination_seeds,
            "travel_window": intake.travel_window.display(),
            "duration_days": intake.duration_days,
            "duration_min_days": intake.duration_min_days,
            "duration_max_days": intake.duration_max_days,
            "duration_display": intake.duration_display(),
            "party": intake.party.model_dump(mode="json"),
            "departure_airports": intake.departure_airports,
            "budget_cad": intake.budget_cad,
            "max_travel_time_hours": intake.max_travel_time_hours,
            "flight_preferences": intake.flight_preferences.model_dump(mode="json"),
            "goals": intake.goals,
            "avoidances": intake.avoidances,
            "pace": intake.pace.value,
            "crowd_tolerance": intake.crowd_tolerance.value,
            "food_priority": intake.food_priority.value,
            "lodging_preferences": intake.lodging_preferences.model_dump(mode="json"),
            "car_rental_expectations": intake.car_rental_expectations.model_dump(mode="json"),
            "freeform_notes": intake.freeform_notes,
        }
        parts = [
            f"# Trippy Trip Shape Generator ({_PROMPT_VERSION})",
            "Build exactly three destination-specific trip shape options for the current intake.",
            "",
            "## Hard Rules",
            "- Respect the user's actual destination seeds. Do not substitute unrelated template destinations.",
            "- Use destination-specific regions, bases, or experience clusters that make sense for the requested destination.",
            "- Optimize Chapman family comfort, food quality, safety, low-friction timing, and practical logistics above raw lowest price.",
            "- Never invent live fares, hotel availability, room layouts, cancellation terms, car inventory, or activity availability.",
            "- If live evidence is needed, put it in required_research or major_risks.",
            "- Make options meaningfully different: low-friction base, balanced best-fit, broader/ambitious version.",
            "- For short trips, punish extra hops and hotel changes hard.",
            "- Use concise strings because this output is rendered in cards.",
            "",
            self._prefs.to_context_string(),
        ]
        if memory_context:
            parts.extend(["", memory_context])
        if country_signals:
            parts.extend(["", "## Matched Country Priors", _json(country_signals)])
        parts.extend(
            [
                "",
                "## Current Intake",
                _json(payload),
                "",
                "## Output JSON Contract",
                _json(
                    {
                        "recommended_option_id": "balanced-best-fit",
                        "assumptions": ["planning assumptions, not live booking claims"],
                        "options": [
                            {
                                "option_id": "short-slug",
                                "title": "card title",
                                "summary": "one sentence",
                                "duration_days": 8,
                                "regions": ["base or region names"],
                                "nights_by_region": {"region": 3},
                                "rationale": ["2-4 bullets"],
                                "travel_burden": "low|moderate|meaningful|high plus why",
                                "island_region_movement_friction": "movement / transfer friction summary",
                                "family_comfort_score": 0,
                                "food_fit": "food fit summary",
                                "driving_fit": "driving / transfers summary",
                                "crowd_fit": "crowd strategy summary",
                                "major_risks": ["risk requiring validation"],
                                "recommendation_strength": 0,
                                "lodging_strategy": "how lodging should work",
                                "car_strategy": "car / transfer strategy",
                                "country_prior_signals": ["matched historical prior, if any"],
                                "map_seed_queries": ["queries to seed later map/source steps"],
                                "required_research": ["live evidence needed before booking"],
                            }
                        ],
                    }
                ),
            ]
        )
        return "\n".join(parts)


def _options_from_payload(payload: dict[str, Any], intake: TripIntake) -> list[TripPlanOption]:
    raw_options = payload.get("options")
    if not isinstance(raw_options, list):
        return []
    options: list[TripPlanOption] = []
    used_ids: set[str] = set()
    for index, raw in enumerate(raw_options[:3], start=1):
        if not isinstance(raw, dict):
            continue
        title = _clean_str(raw.get("title")) or f"{_destination_label(intake)} Option {index}"
        option_id = _slug(_clean_str(raw.get("option_id")) or title)
        if option_id in used_ids:
            option_id = f"{option_id}-{index}"
        used_ids.add(option_id)
        regions = _string_list(raw.get("regions")) or intake.destination_seeds[:1]
        duration_days = _int(raw.get("duration_days"), intake.duration_days or 8)
        nights = _nights(raw.get("nights_by_region"), regions, duration_days)
        options.append(
            TripPlanOption(
                option_id=option_id,
                title=title,
                summary=_clean_str(raw.get("summary"))
                or "Destination-specific trip shape generated from the intake.",
                duration_days=duration_days,
                regions=regions,
                nights_by_region=nights,
                rationale=_string_list(raw.get("rationale"))[:4]
                or ["Generated from the selected destination and current intake."],
                travel_burden=_clean_str(raw.get("travel_burden"))
                or "requires live flight validation",
                island_region_movement_friction=_clean_str(
                    raw.get("island_region_movement_friction")
                )
                or "Requires transfer and drive-time validation.",
                family_comfort_score=_score(raw.get("family_comfort_score"), 75),
                food_fit=_clean_str(raw.get("food_fit"))
                or "Needs destination-specific food cluster research.",
                driving_fit=_clean_str(raw.get("driving_fit"))
                or "Validate driving, transfers, parking, and road comfort.",
                crowd_fit=_clean_str(raw.get("crowd_fit"))
                or "Use timing and base selection to avoid crowd friction.",
                major_risks=_string_list(raw.get("major_risks"))[:4]
                or ["Exact logistics and availability need live validation."],
                recommendation_strength=_score(raw.get("recommendation_strength"), 70),
                lodging_strategy=_clean_str(raw.get("lodging_strategy"))
                or intake.lodging_preferences.non_city_strategy,
                car_strategy=_clean_str(raw.get("car_strategy"))
                or "Compare rental car against private transfers and day-trip operators.",
                country_prior_signals=_string_list(raw.get("country_prior_signals"))[:4],
                map_seed_queries=_string_list(raw.get("map_seed_queries"))[:10]
                or regions,
                required_research=_string_list(raw.get("required_research"))[:8]
                or _default_required_research(),
            )
        )
    return options


def _nights(value: Any, regions: list[str], duration_days: int) -> dict[str, int]:
    if isinstance(value, dict):
        cleaned: dict[str, int] = {}
        for key, raw in value.items():
            label = str(key).strip()
            nights = _int(raw, 0)
            if label and nights > 0:
                cleaned[label] = nights
        if cleaned:
            return cleaned
    nights_total = max(1, duration_days - 1)
    base = nights_total // max(1, len(regions))
    extra = nights_total % max(1, len(regions))
    return {
        region: base + (1 if index < extra else 0)
        for index, region in enumerate(regions)
    }


def _default_required_research() -> list[str]:
    return [
        "Live flight options, total travel time, layovers, baggage, seats, and loyalty application.",
        "Exact lodging shortlist with bed layout, location, safety, parking/access, and cancellation terms.",
        "Car or transfer fit, pickup/dropoff clarity, hidden fees, and cancellation terms.",
        "Small-group activities/tours with strong review and safety signals.",
        "Entry requirements, passport validity, health precautions, local cash guidance, and seasonality.",
    ]


def _destination_label(intake: TripIntake) -> str:
    return ", ".join(intake.destination_seeds) or intake.trip_name or "Destination"


def _response_text(response: Any) -> str:
    parts: list[str] = []
    for block in getattr(response, "content", []):
        if getattr(block, "type", "") == "text":
            parts.append(str(getattr(block, "text", "")))
    return "\n".join(part for part in parts if part).strip()


def _parse_json_response(text: str) -> dict[str, Any]:
    stripped = text.strip()
    if stripped.startswith("```"):
        stripped = stripped.strip("`").strip()
        if stripped.startswith("json"):
            stripped = stripped.removeprefix("json").strip()
    try:
        data = json.loads(stripped)
    except json.JSONDecodeError:
        start = stripped.find("{")
        end = stripped.rfind("}")
        if start == -1 or end == -1 or end <= start:
            raise
        data = json.loads(stripped[start : end + 1])
    if not isinstance(data, dict):
        raise ValueError("LLM trip-shape response must be a JSON object")
    return data


def _string_list(value: Any) -> list[str]:
    if value is None:
        return []
    if isinstance(value, str):
        return [item.strip() for item in value.split(",") if item.strip()]
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    return [str(value).strip()] if str(value).strip() else []


def _clean_str(value: Any) -> str:
    return str(value or "").strip()


def _int(value: Any, default: int) -> int:
    try:
        return int(float(str(value).strip()))
    except (TypeError, ValueError):
        return default


def _score(value: Any, default: int) -> int:
    return max(0, min(100, _int(value, default)))


def _slug(value: str) -> str:
    slug = re.sub(r"[^a-z0-9]+", "-", value.lower()).strip("-")
    return slug or "llm-option"


def _json(value: Any) -> str:
    return json.dumps(value, indent=2, sort_keys=True, default=str)
